import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';
import { nodePolyfills } from 'vite-plugin-node-polyfills';

// Note: src/generated-env.ts is generated by scripts/generate-env.mjs
// which runs automatically before dev/build via npm predev/prebuild scripts

export default defineConfig({
  plugins: [react(), nodePolyfills()],
  envPrefix: 'VITE_',
  define: {
    global: 'globalThis',
  },
  build: {
    outDir: 'dist',
    emptyOutDir: true
  },
  optimizeDeps: {
    esbuildOptions: {
      define: {
        global: 'globalThis'
      }
    }
  },
  server: {
    proxy: {
      '/api': {
        target: 'http://localhost:3001',
        changeOrigin: true,
      }
    }
  }
});
