#!/usr/bin/env node
/**
 * Generate src/generated-env.ts from .env file
 * This bypasses shell environment variable override issues
 */
import * as fs from 'fs';
import * as path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const projectRoot = path.resolve(__dirname, '..');

function loadEnvFile() {
  const envPath = path.resolve(projectRoot, '.env');
  const envValues = {};
  if (fs.existsSync(envPath)) {
    const content = fs.readFileSync(envPath, 'utf8');
    for (const line of content.split('\n')) {
      const trimmed = line.trim();
      if (trimmed && !trimmed.startsWith('#')) {
        const eqIndex = trimmed.indexOf('=');
        if (eqIndex > 0) {
          const key = trimmed.slice(0, eqIndex);
          const value = trimmed.slice(eqIndex + 1);
          if (key.startsWith('VITE_')) {
            envValues[key] = value;
          }
        }
      }
    }
  }
  return envValues;
}

const envFromFile = loadEnvFile();

// Check process.env first (for Vercel/CI), then .env file (for local dev)
const getValue = (key) => process.env[key] || envFromFile[key] || '';

const envConfigContent = `// Auto-generated - DO NOT EDIT
// This file is generated by scripts/generate-env.mjs from .env
// Run: npm run generate-env (automatically runs before dev/build)
export const ASSET_CONTRACT = ${JSON.stringify(getValue('VITE_ASSET_CONTRACT'))};
export const MARKETPLACE_CONTRACT = ${JSON.stringify(getValue('VITE_MARKETPLACE_CONTRACT'))};
`;

const outputPath = path.resolve(projectRoot, 'src/generated-env.ts');
fs.writeFileSync(outputPath, envConfigContent);
console.log('Generated src/generated-env.ts from .env');
